/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MenuPrincipalController;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author stephens
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    MenuPrincipalController controller;
    Usuario usuarioLogado; 
    
    public MenuPrincipal() {
        initComponents();
        controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameTelaBemVindo = new javax.swing.JInternalFrame();
        jPanelBemVindo = new javax.swing.JPanel();
        jButtonMedicoBemVindo = new javax.swing.JButton();
        jButtonPacienteBemVindo = new javax.swing.JButton();
        jButtonEnfemeiraBemVindo = new javax.swing.JButton();
        jButtonAgendaBemVinbdo = new javax.swing.JButton();
        jLabelOpcoesBemVindo = new javax.swing.JLabel();
        jLabelAvisoBemVindo = new javax.swing.JLabel();
        jLabelCadastrosBemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoPanelBemVinco = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadMedicos = new javax.swing.JMenuItem();
        jMenuItemCadPacientes = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeiras = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemConsultas = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Médica");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameTelaBemVindo.setClosable(true);
        jInternalFrameTelaBemVindo.setTitle("Bem-Vindo");
        jInternalFrameTelaBemVindo.setVisible(true);
        jInternalFrameTelaBemVindo.getContentPane().setLayout(null);

        jPanelBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBemVindo.setLayout(null);

        jButtonMedicoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/CadMedicos.png"))); // NOI18N
        jButtonMedicoBemVindo.setToolTipText("Cadastro de Médicos");
        jButtonMedicoBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoBemVindoActionPerformed(evt);
            }
        });
        jPanelBemVindo.add(jButtonMedicoBemVindo);
        jButtonMedicoBemVindo.setBounds(20, 50, 100, 110);

        jButtonPacienteBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/cadPacientes.png"))); // NOI18N
        jButtonPacienteBemVindo.setToolTipText("Cadastro de Pacientes");
        jButtonPacienteBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteBemVindoActionPerformed(evt);
            }
        });
        jPanelBemVindo.add(jButtonPacienteBemVindo);
        jButtonPacienteBemVindo.setBounds(120, 50, 100, 110);

        jButtonEnfemeiraBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icon-infermeira.png"))); // NOI18N
        jButtonEnfemeiraBemVindo.setToolTipText("Cadastro de Enfermeira(o)s");
        jButtonEnfemeiraBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnfemeiraBemVindoActionPerformed(evt);
            }
        });
        jPanelBemVindo.add(jButtonEnfemeiraBemVindo);
        jButtonEnfemeiraBemVindo.setBounds(220, 50, 110, 110);

        jButtonAgendaBemVinbdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda.png"))); // NOI18N
        jButtonAgendaBemVinbdo.setToolTipText("Agenda");
        jButtonAgendaBemVinbdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaBemVinbdoActionPerformed(evt);
            }
        });
        jPanelBemVindo.add(jButtonAgendaBemVinbdo);
        jButtonAgendaBemVinbdo.setBounds(20, 190, 100, 110);

        jLabelOpcoesBemVindo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelOpcoesBemVindo.setText("Opções de Navegação");
        jPanelBemVindo.add(jLabelOpcoesBemVindo);
        jLabelOpcoesBemVindo.setBounds(120, 10, 190, 20);

        jLabelAvisoBemVindo.setText("Passe o cursos em cima da imagem...");
        jPanelBemVindo.add(jLabelAvisoBemVindo);
        jLabelAvisoBemVindo.setBounds(170, 280, 310, 14);

        jLabelCadastrosBemVindo.setText("Cadastros:");
        jPanelBemVindo.add(jLabelCadastrosBemVindo);
        jLabelCadastrosBemVindo.setBounds(20, 30, 80, 20);

        jLabel1.setText("Agenda:");
        jPanelBemVindo.add(jLabel1);
        jLabel1.setBounds(20, 170, 80, 14);

        jLabelFundoPanelBemVinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/internalframe.png"))); // NOI18N
        jPanelBemVindo.add(jLabelFundoPanelBemVinco);
        jLabelFundoPanelBemVinco.setBounds(-260, -10, 900, 330);

        jInternalFrameTelaBemVindo.getContentPane().add(jPanelBemVindo);
        jPanelBemVindo.setBounds(10, 10, 620, 310);

        getContentPane().add(jInternalFrameTelaBemVindo);
        jInternalFrameTelaBemVindo.setBounds(0, 0, 660, 360);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 660, 370);

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadMedicos.setText("Médicos");
        jMenuItemCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadMedicos);

        jMenuItemCadPacientes.setText("Pacientes");
        jMenuItemCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadPacientes);

        jMenuItemCadEnfermeiras.setText("Enfermeiras");
        jMenuItemCadEnfermeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnfermeirasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadEnfermeiras);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemConsultas.setText("Consultas");
        jMenuItemConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultasActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemConsultas);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(675, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadEnfermeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnfermeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadEnfermeirasActionPerformed

    private void jMenuItemCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacientesActionPerformed
        controller.ativaCadPaciente(usuarioLogado);
    }//GEN-LAST:event_jMenuItemCadPacientesActionPerformed

    private void jButtonEnfemeiraBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnfemeiraBemVindoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnfemeiraBemVindoActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameTelaBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicosActionPerformed
        controller.ativaCadMedico(usuarioLogado);
    }//GEN-LAST:event_jMenuItemCadMedicosActionPerformed

    private void jButtonMedicoBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoBemVindoActionPerformed
        controller.ativaCadMedico(usuarioLogado);
    }//GEN-LAST:event_jButtonMedicoBemVindoActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        controller.ativaCadUsuario(usuarioLogado);
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jButtonPacienteBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteBemVindoActionPerformed
        controller.ativaCadPaciente(usuarioLogado);
    }//GEN-LAST:event_jButtonPacienteBemVindoActionPerformed

    private void jButtonAgendaBemVinbdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaBemVinbdoActionPerformed
        controller.artivaAgendamento(usuarioLogado);
    }//GEN-LAST:event_jButtonAgendaBemVinbdoActionPerformed

    private void jMenuItemConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultasActionPerformed
        controller.ativaConsultas();
    }//GEN-LAST:event_jMenuItemConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendaBemVinbdo;
    private javax.swing.JButton jButtonEnfemeiraBemVindo;
    private javax.swing.JButton jButtonMedicoBemVindo;
    private javax.swing.JButton jButtonPacienteBemVindo;
    private javax.swing.JInternalFrame jInternalFrameTelaBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvisoBemVindo;
    private javax.swing.JLabel jLabelCadastrosBemVindo;
    private javax.swing.JLabel jLabelFundoPanelBemVinco;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelOpcoesBemVindo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadEnfermeiras;
    private javax.swing.JMenuItem jMenuItemCadMedicos;
    private javax.swing.JMenuItem jMenuItemCadPacientes;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemConsultas;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBemVindo;
    // End of variables declaration//GEN-END:variables

public void recebeUsuarioLogado(Usuario usuario){
        this.usuarioLogado = usuario;
    }



}

